contactos/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from . import views, views_agente, views_agenda, parametros_views
from . import calificaciones_views

urlpatterns = [
    path('contacto/', views.ContactoListView.as_view(), name='tc-contacto'),
    path('contacto/ajax/', views.ContactoListAjaxView.as_view(), name='tc-contacto-ajax'),
    path('contacto/add/', views.ContactoAddView.as_view(), name='tc-contacto-add'),
    path('contacto/add/ajax/', views.ContactoAddAjaxView.as_view(), name='tc-contacto-add-ajax'),
    # path('contacto/<int:pk>/detail/', views.ContactoDetailView.as_view(), name='tc-contacto-detail'),
    path('contacto/<int:pk>/update/', views.ContactoUpdateView.as_view(), name='tc-contacto-update'),
    re_path(r'contacto/calificar_llamada/(?P<call_data_json>.+)/$', views.ContactoCalificarLlamadaView.as_view(),
        name='tc-contacto-calificar'
    ),
    path('contacto/identificar_llamada/', views.ContactoIdentificarLlamadaView.as_view(),
        name='tc-contacto-identificar'
    ),

    path('contacto/buscar/documento/',      views.BuscarDocumentoAjax,      name='tc-buscar-documento-ajax'),

    path('contacto/<int:pk>/gestion/',      views.ContactoGestionView.as_view(), name='tc-contacto-gestion'),
    path('contacto/<int:pk>/gestion/add/',  views.ContactoGestionAddAjaxView.as_view(), name='tc-contacto-gestion-add-ajax'),

    path('contacto/<int:pk>/telefono/',     views.ContactoTelefonoList.as_view(), name='tc-contacto-telefono'),
    path('contacto/telefono/add/',          views.ContactoTelefonoAdd.as_view(), name='tc-contacto-telefono-add'),
    path('contacto/telefono/delete/',       views.ContactoTelefonoDelete.as_view(), name='tc-contacto-telefono-delete'),

    path('eliminar/telefono/ajax/view/', views.EliminarTelefonoAjaxView.as_view(), name='tc_eliminar-telefono-ajax'),
    path('editar/telefono/ajax/view/', views.EditarTelefonoAjaxView.as_view(), name='tc_editar-telefono-ajax'),

    path('contacto/<int:pk>/email/',        views.ContactoEmailList.as_view(), name='tc-contacto-email'),
    path('contacto/email/add/',             views.ContactoEmailAdd.as_view(), name='tc-contacto-email-add'),
    path('contacto/email/delete/',          views.ContactoEmailDelete.as_view(), name='tc-contacto-email-delete'),

    path('contacto/<int:pk>/direccion/',    views.ContactoDireccionList.as_view(), name='tc-contacto-direccion'),
    path('contacto/direccion/add/',         views.ContactoDireccionAdd.as_view(), name='tc-contacto-direccion-add'),
    path('contacto/direccion/delete/',      views.ContactoDireccionDelete.as_view(), name='tc-contacto-direccion-delete'),

    path('contacto/<int:pk>/dialogo/',     views.ContactoDialogoList.as_view(), name='tc-contacto-dialogo'),
    path('contacto/<int:pk>/numeros/',     views.ContactoNumerosList.as_view(), name='tc-numeros'),

    path('gestion/<int:pk>/',           views.GestionView.as_view(), name='tc-gestion'),
    path('gestion/cargar/',             views.GestionCargarView.as_view(), name='tc-gestion-cargar'),


    path('test_template/', views.TestTemplateView.as_view(), name='tc-test-template'),

    # =======================   AGENDA CONTACTOS ======================////

    path('contacto/programacion/list/', views_agenda.ProgramacionListView.as_view(), name='tc-programacion-list'),
    path('contacto/programacion/add/', views_agenda.ProgramacionAddView.as_view(), name='tc-programacion-add'),
    path('contacto/programacion/<int:pk>/update/', views_agenda.ProgramacionUpdateView.as_view(), name='tc-programacion-update'),


    # ======================== VISTAS DE OMNILEADS RE UTILIZADAS =========================
    path('agente/llamar/',
        login_required(views_agente.LlamarContactoView.as_view() ),
        name='tc-agente-llamar-contacto', ),

    # =======================   PARAMETROS ======================////
    path('parametros/agentes/permisos', parametros_views.AgentesPermisosView.as_view(), name='agentes-permisos'),
    path('parametros/formulario_configuracion/', parametros_views.FormularioConfiguracion.as_view(), name='configuracion-formulario'),

    path('parametros/resultado/', parametros_views.ResultadoGestionView.as_view(), name='resultado-list'),
    path('parametros/resultado/add/', parametros_views.ResultadoGestionCreateView.as_view(), name='resultado-create'),
    path('parametros/resultado/<int:pk>/update/', parametros_views.ResultadoGestionUpdateView.as_view(), name='resultado-update'),
    path('parametros/resultado/consulta/', parametros_views.ResultadosGestionAjax, name='resultados_ajax'),

    path('parametros/calificacion/', parametros_views.CalificacionGestionView.as_view(), name='calificacion-list'),
    path('parametros/calificacion/add/', parametros_views.CalificacionGestionCreateView.as_view(), name='calificacion-create'),
    path('parametros/calificacion/<int:pk>/update/', parametros_views.CalificacionGestionUpdateView.as_view(), name='calificacion-update'),
    path('parametros/calificacion/consulta/', parametros_views.CalificacionGestionAjax, name='calificacion_ajax'),
    
    path('parametros/tipo/', parametros_views.TipoGestionView.as_view(), name='tipo-list'),
    path('parametros/tipo/add/', parametros_views.TipoGestionCreateView.as_view(), name='tipo-create'),
    path('parametros/tipo/<int:pk>/update/', parametros_views.TipoGestionUpdateView.as_view(), name='tipo-update'),

    # Funciones AJAX para nuevo TC
    path('gestion/ajax/telefonia/',         views.GestionTelefoniaViewAjax.as_view(),   name='tc-gestion-ajax-telefonia'),
    path('contacto/ajax/view/',             views.ContactoAjaxView.as_view(),           name='tc-contacto-ajax-ver'),
    path('contacto/ajax/update/',           views.ContactoAjaxUpdate.as_view(),         name='tc-contacto-ajax-update'),
    path('contacto/ajax/gestionar/',        views.ContactoAjaxGestionar.as_view(),      name='tc-contacto-ajax-gestionar'),
    path('contacto/add/ajax/telefono/',     views.ContactoAddAjaxTelefono.as_view(),    name='tc-contacto-telefono-add-ajax'),
    path('contacto/add/ajax/correo/',       views.ContactoAddAjaxCorreo.as_view(),      name='tc-contacto-correo-add-ajax'),
    path('contacto/add/ajax/direccion/',    views.ContactoAddAjaxDireccion.as_view(),   name='tc-contacto-direccion-add-ajax'),
    path('contacto/validar/ajax/telefono/', views.ContactoValidarTelefonoAjax.as_view(),name='tc-validar-telefono-ajax'),
    path('validar/whastapp/ajax/',          views.ValidarWhastappAjax.as_view(),        name='tc-validar-whatsapp-ajax'),

    path('gestion/ajax/guardar',        views.GestionGuardarAjax.as_view(),     name='tc_gestion-ajax-guardar'),
    path('gestion/ajax/consulta/',      views.GestionViewAjax.as_view(),        name='tc_gestion-ajax-consulta'),

                           ############# Calificaciones Views ####################

    path('contacto/calificacion/list/', calificaciones_views.CalificacionListView.as_view(), name='tc-contacto-calificacion-list'),
    path('contacto/calificacion/<int:pk>/update/',calificaciones_views.CalificacionUpdateView.as_view(),name='tc-contacto-calificacion-update'),                      
    path('contacto/calificacion/add/', calificaciones_views.CalificacionAddView.as_view(),name='tc-contacto-calificacion-add'),

    path('agente/contacto/campana/', views.AgenteContactoCampanas.as_view(),name='tc-agente-contacto-campana'),
    path('contacto/calificacion/campana/', views.ContactoCalificacionCampanas.as_view(),name='tc-contacto-calificacion-campana'),

                           ############# Vistas relacionadas callcenter shaio ####################

    path('buscarmotivo/resultados/', views_agente.ObtenerDetalleMotivo.as_view(), name="tc-obtener-resultado-motivo"),

]

contactos/forms.py
from django import forms
from truecontact.chatapi.models import Dialogo, Mensaje
from ominicontacto_app.models import Campana


from truecontact.contactos.models import (Contacto, ContactoDatosContacto, Programacion,
    TipoIdentificacion, CalificacionGestion)


from .models import *

import ast
import datetime as dt
import pytz

class AgregarContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['nombres', 'apellidos', 'imagen', 'tipo_identificacion', 'documento', 'genero', 'cargo', 'nacimiento',
            'sitioweb', 'es_compania', 'ciudad', 'codigo_postal', 'industria', 'observaciones_contacto',
            'bool_1', 'bool_2', 'bool_3',
        ]




class GestionContactoForm(forms.ModelForm):
    # def __init__(self, campanas_ids=None, *args, **kwargs):

    #     print("PREPARANDO..........................<<<<<<<<<<<<<<<<<<<<<<<<<<<")
    #     print("filtrando camapanas: ", campanas_ids)
    #     queryset_calificaciones = []
    #     if campanas_ids:
    #         print("filtrando camapanas: ", campanas_ids)
    #         for campanapk in campanas_ids:
    #             print("buscando", campanapk)
    #             campana = Campana.objects.get(pk = campanapk)
    #             queryset_calificaciones.extend(list(CalificacionGestion.objects.filter(campana=campana)))
    #             print("CALIFICACIONES....................", queryset_calificaciones)
    #         self.fields['calificacion'].queryset = queryset_calificaciones
    class Meta:
        model = GestionContacto
        fields = [ 'tipo', 'medio', 'resultado', 'calificacion', 'contacto', 'metadata', 'observaciones']

class GestionContactoForm1(forms.ModelForm):
    class Meta:
        model = GestionContacto
        fields = [ 'tipo', 'medio', 'motivo', 'resul', 'especialidad', 'entidad', 'tipo_consulta','observaciones', 'tyc']

class GestionContactoFormViejo(forms.Form):
    gestion = forms.CharField(widget=forms.HiddenInput, required=False)
    contacto = forms.CharField(widget=forms.HiddenInput)
    call_data = forms.CharField(widget=forms.HiddenInput, required=True)
    tipo = forms.ModelChoiceField(
        queryset = TipoGestion.objects.all().order_by("nombre"),
        empty_label="Seleccione",
        required=True
    )
    medio = forms.CharField(widget=forms.HiddenInput, required=True)
    resultado = forms.ModelChoiceField(
        queryset = ResultadoGestion.objects.all().order_by("nombre"),
        empty_label="Seleccion",
        required=True
    )

    observaciones = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(GestionContactoForm, self).__init__(*args, **kwargs)
        if 'initial' in kwargs:
            pass
            if 'tipo' in kwargs['initial']:
                lista_resultado = ResultadoGestion.objects.filter(tipogestion__nombre__icontains=kwargs['initial']['tipo'])
                self.fields['resultado'] = forms.ModelChoiceField(queryset=lista_resultado, empty_label="Seleccione", required=True)
            # if 'medio' in kwargs['initial']:
            #     lista_resultado = ResultadoGestion.objects.filter(tipogestion__nombre__icontains=kwargs['initial']['medio'])
            #     self.fields['resultado'] = forms.ModelChoiceField(queryset=lista_resultado, empty_label="Seleccione", required=True)


    def save(self, user, contacto):
        print ("CLEANED DATA: ", self.cleaned_data)
        id_gestion = self.cleaned_data['gestion']
        resultado = self.cleaned_data['resultado']
        # calificacion = self.cleaned_data['calificacion']
        metadata = self.cleaned_data['call_data']
        observaciones = self.cleaned_data['observaciones']
        tipo = self.cleaned_data['tipo']
        medio = self.cleaned_data['medio']


        if not(id_gestion == '' or id_gestion == None):
            gestion = GestionContacto.objects.get(pk=id_gestion)
            gestion.resultado = resultado
            # gestion.calificacion = calificacion
            gestion.modificado_por = user
            gestion.fecha_finalizacion = dt.datetime.now()
            gestion.estado = 'finalizado'
            gestion.observaciones = observaciones
            medio = gestion.medio

        else:
            gestion = GestionContacto(
                tipo = tipo,
                medio = medio,
                resultado = resultado,
                # calificacion = calificacion,
                contacto = contacto,
                creado_por = user,
                modificado_por = user,
                fecha_finalizacion = dt.datetime.now(),
                metadata = metadata,
                estado = 'finalizado',
                observaciones = observaciones,
            )

        if (medio == 'whatsapp'):
            call_data = ast.literal_eval(gestion.metadata)
            dialogo = Dialogo.objects.get(pk=call_data['chat_id'])
            dialogo.estado = 'gestionado'
            dialogo.fecha_modificacion = dt.datetime.now(pytz.utc)
            dialogo.user = None
            dialogo.ultimo_mensaje_gestion = (Mensaje.objects
                                .obtener_ultimo_mensaje(
                                    dialogo=dialogo
                                )['ultimo_mensaje_numero'])
            dialogo.save()
            call_data['mensaje_final'] = dialogo.ultimo_mensaje_gestion
            gestion.metadata = call_data

        gestion.save()
        return gestion

class TelefonoForm(forms.Form):
    contacto = forms.CharField(widget=forms.HiddenInput)
    label = forms.CharField(max_length=32)
    tipo = 'telefono'
    telefono = forms.CharField(max_length=256)

    def validate(self):
        contacto = self.cleaned_data['contacto']
        label = self.cleaned_data['label']
        telefono = self.cleaned_data['telefono']
        return 0

    def save(self):
        contacto = Contacto.objects.get(pk=self.cleaned_data['contacto'])
        label = self.cleaned_data['label']
        telefono = self.cleaned_data['telefono']
        print ("""
            contacto_id: {}\n
            label: {}\n
            telefono: {}
        """.format(contacto.pk, label, telefono))
        contacto_datocontacto = ContactoDatosContacto.objects.create(
            contacto = contacto,
            label = label,
            tipo = self.tipo,
            value_1 = telefono,
        )
        return {
                    'status': 'ok',
                    'telefono': {
                        'id': contacto_datocontacto.pk,
                        'label': contacto_datocontacto.get_label_display(),
                        'telefono': contacto_datocontacto.value_1,
                    }
                }

class EmailForm(forms.Form):
    contacto = forms.CharField(widget=forms.HiddenInput)
    label = forms.CharField(max_length=32)
    tipo = 'email'
    email = forms.CharField(max_length=256)

    def validate(self):
        contacto = self.cleaned_data['contacto']
        label = self.cleaned_data['label']
        email = self.cleaned_data['email']
        return 0

    def save(self):
        contacto = Contacto.objects.get(pk=self.cleaned_data['contacto'])
        label = self.cleaned_data['label']
        email = self.cleaned_data['email']
        print ("""
            contacto_id: {}\n
            label: {}\n
            email: {}
        """.format(contacto.pk, label, email))
        contacto_datocontacto = ContactoDatosContacto.objects.create(
            contacto = contacto,
            label = label,
            tipo = self.tipo,
            value_1 = email,
        )
        return {
                    'status': 'ok',
                    'email': {
                        'id': contacto_datocontacto.pk,
                        'label': contacto_datocontacto.get_label_display(),
                        'email': contacto_datocontacto.value_1,
                    }
                }

class DireccionForm(forms.Form):
    contacto = forms.CharField(widget=forms.HiddenInput)
    label = forms.CharField(max_length=32)
    tipo = 'direccion'
    calle_1 = forms.CharField(max_length=256)
    calle_2 = forms.CharField(max_length=256, required=False)
    codigo_postal = forms.CharField(max_length=256, required=False)
    ciudad = forms.CharField(max_length=256)
    pais = forms.CharField(max_length=256)

    def validate(self):
        return 0

    def save(self):
        contacto = Contacto.objects.get(pk=self.cleaned_data['contacto'])
        label = self.cleaned_data['label']
        calle_1 = self.cleaned_data['calle_1']
        calle_2 = self.cleaned_data['calle_2']
        codigo_postal = self.cleaned_data['codigo_postal']
        ciudad = self.cleaned_data['ciudad']
        pais = self.cleaned_data['pais']
        print ("""
            contacto_id: {}\n
            label: {}\n
            calle_1: {}\n
            calle_2: {}\n
            codigo_postal: {}\n
            ciudad: {}\n
            pais: {}\n
        """.format(contacto.pk, label, calle_1, calle_2, codigo_postal, ciudad, pais))
        contacto_datocontacto = ContactoDatosContacto.objects.create(
            contacto = contacto,
            label = label,
            tipo = self.tipo,
            value_1 = calle_1,
            value_2 = calle_2,
            value_3 = codigo_postal,
            value_4 = ciudad,
            value_5 = pais,
        )
        return {
                    'status': 'ok',
                    'direccion': {
                        'id': contacto_datocontacto.pk,
                        'label': contacto_datocontacto.get_label_display(),
                        'calle_1': contacto_datocontacto.value_1,
                        'calle_2': contacto_datocontacto.value_2,
                        'codigo_postal': contacto_datocontacto.value_3,
                        'ciudad': contacto_datocontacto.value_4,
                        'pais': contacto_datocontacto.value_5,
                    }
                }

contactos/templates/contactos/contacto_identificar.html
{% extends 'truecontact/base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block page_css_level %}
{% endblock %}

{% block content %}
<div class="content">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6">
          <h3 class="mr-2 text-dark float-left">Gestion</h3>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="card">
        <div class="card-header">
          <form id="form-buscar-contacto" class="form-horizontal" action="" method="get">
            <div class="row">
              <div class="col-sm-6">
                <h4 class="text-muted"> Se encontraron {{ contactos_encontrados }} contactos con este numero de telefono.</h4>
              </div>
              <div class="col-sm-5">
                <div class="input-group input-group-sm">
                  <input type="hidden" name="call_data" value="{{ call_data }}">
                  <input type="text" name="buscar" class="form-control" value="{{ buscar }}" placeholder="nombre, documento">
                  <span class="input-group-append">
                    <button id="contacto_identificar_buscar" type="button" class="btn btn-info btn-flat">
                      Buscar
                    </button>
                  </span>
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class="card-body">
          <div class="row">
            <table id="table-contactos" class="table table-hover">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Cargo</th>
                  <th class="text-center">Accion</th>
                </tr>
              </thead>
              <tbody>
                {% for contacto in contactos %}
                  <tr>
                    <td>
                      {{ contacto.get_full_name }}
                    </td>
                    <td>
                      {{ contacto.cargo }}
                    </td>
                    <td class="text-center">
                      <button type="button" class="btn btn-sm btn-info" onclick="gestionarContacto(this)" data-id="{{ contacto.pk }}">
                        Gestionar
                      </button>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer clearfix">
          <h5 class="text-muted"> En caso de no encontrar el contacto a gestionar, por favor crearlo para
          continuar</h5>
          <button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#modal-agregar-contacto">
            Agregar Contacto
          </button>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  <!-- modal agregar cliente -->
  <div class="modal fade" id="modal-agregar-contacto">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Agregar Contacto</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form id="form-agregar-contacto" class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card card-primary card-outline">
              <div class="card-body box-profile text-center">
                <div class="text-center">
                  <img id="profile-image-upload" class="profile-img-card img-fluid img-circle" src="{% static 'truecontact/adminlte/assets/img/default-user.png' %}" alt="User profile picture">
                  <div id="profile-image-input">
                    {% render_field form.imagen class="form-control"%}
                  </div>
                </div>
                <h3 class="profile-username">
                  {% render_field form.nombres class="form-control" placeholder="Nombres" data-toggle="tooltip" data-placement="top" title="Nombres" %}
                  {% for error in form.nombres.errors %}
                    <p class="text-danger">{{ error }}</p>
                  {% endfor %}
                </h3>
                <h3 class="profile-username">
                  {% render_field form.apellidos class="form-control" placeholder="apellidos" data-toggle="tooltip" data-placement="top" title="apellidos" %}
                  {% for error in form.apellidos.errors %}
                    <p class="text-danger">{{ error }}</p>
                  {% endfor %}
                </h3>

                <!-- <h3 class="text-muted">
                  {% render_field form.documento class="form-control" placeholder="Documento" data-toggle="tooltip" data-placement="top" title="Documento" %}
                  {% for error in form.documento.errors %}
                    <p class="text-danger">{{ error }}</p>
                  {% endfor %}
                </h3> -->
                <!-- <p class="text-muted">
                  {% render_field form.cargo class="form-control" placeholder="Cargo" data-toggle="tooltip" data-placement="top" title="Cargo" %}
                  {% for error in form.cargo.errors %}
                    <p class="text-danger">{{ error }}</p>
                  {% endfor %}
                </p> -->
                <ul class="ml-4 fa-ul text-muted">
                  <li class="small mb-1"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span>
                    {% render_field form.direccion class="form-control form-control-sm" placeholder="Direccion" data-toggle="tooltip" data-placement="top" title="Dirección" %}
                    {% for error in form.cargo.errors %}
                      <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                  </li>
                  <li class="small mb-1"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span>
                    <input class="form-control form-control-sm disable" data-placement="top"
                      data-toggle="tooltip" id="id_telefono" maxlength="512" name="telefono"
                      placeholder="Telefono" title="Telefono" type="text" value="{{ telefono }}"
                    >
                    {% for error in form.cargo.errors %}
                      <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                  </li>
                  <!-- <li class="small mb-1"><span class="fa-li"><i class="fas fa-lg fa-at"></i></span>
                    {% render_field form.email class="form-control form-control-sm" placeholder="Email" data-toggle="tooltip" data-placement="top" title="Email" %}
                    {% for error in form.cargo.errors %}
                      <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                  </li> -->
                </ul>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <ul id="error-agregar-contacto" class="text-danger">
                </ul>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id="btn-guardar-contacto" type="button" class="btn btn-info">Guardar y Gestionar</button>
        </div>
      </div>
    </div>
  </div>
  <!-- ./ modal agregar cliente-->
</div>
{% endblock %}

{% block page_js_level %}
<script type="text/javascript">

  toastr.options.closeButton = true;
  toastr.options.closeDuration = 100;

  const btn_identificar_buscar = document.getElementById('contacto_identificar_buscar').addEventListener('click', function() {
    buscarContacto();
  });

  function buscarContacto(){
    let call_data = document.querySelector('input[name="call_data"]').value;
  };

  function gestionarContacto(element){
    let id_contacto = element.getAttribute('data-id');
    let call_data = document.querySelector('input[name="call_data"]').value;
    if (call_data != ''){
      let call_data_json = JSON.parse(call_data);
      call_data_json['id_contacto'] = id_contacto;
      const url = Urls.tc_contacto_calificar(encodeURIComponent(JSON.stringify(call_data_json)));
      window.location.href = url;
    }else{
      toastr.error('Error al gestionar el contacto, por favor contacte con su administrador');
    }
  };


  $(document).ready(function() {
    $("#profile-image-upload").click(function(e) {
      $("#id_imagen").click();
    });

    function fasterPreview( uploader ) {
      if ( uploader.files && uploader.files[0] ){
        $('#profile-image-upload').attr('src', window.URL.createObjectURL(uploader.files[0]) );
      }
    }

    $("#id_imagen").change(function(){
        fasterPreview( this );
    });

    $("#form-buscar-contacto").keypress(function(e) {
      //Enter key
      if (e.which == 13) {
        return false;
      }
    });

    $("#contacto_identificar_buscar").click(function() {
      const url = Urls.tc_contacto_ajax();
      $.get(url, $("#form-buscar-contacto").serialize(), function(data, status) {
        let respuesta = data;
        if (respuesta['status'] == 'ok') {
          const lista_contactos = document.querySelector('#table-contactos tbody');
          lista_contactos.innerHTML = '';
          const contactos = respuesta['contactos'];
          contactos.forEach((contacto, i) => {
            let tr_contacto = document.createElement('tr');
            tr_contacto.innerHTML = `
              <tr>
                <td>
                  ${contacto['nombres']} ${contacto['apellidos']}
                </td>
                <td>
                  ${contacto['cargo']}
                </td>
                <td class="text-center">
                  <button type="button" class="btn btn-sm btn-info" onclick="gestionarContacto(this)" data-id="${contacto['id']}">
                    Gestionar
                  </button>
                </td>
              </tr>
            `;
            lista_contactos.appendChild(tr_contacto);
          });

        }else{
          console.log("cero encontrados");
        }
      });
    });

    $("#btn-guardar-contacto").click(function (){
      const url = Urls.tc_contacto_add_ajax();
      $.post(url, $("#form-agregar-contacto").serialize(), function(data, status){
				if (status=="success") {
					let respuesta = data;
          if (respuesta['status'] == 'ok'){
            let id_contacto = respuesta['contacto_id'];
            let call_data = document.querySelector('input[name="call_data"]').value;
            if (call_data != ''){
              let call_data_json = JSON.parse(call_data);
              call_data_json['id_contacto'] = id_contacto;
              const url = Urls.tc_contacto_calificar(encodeURIComponent(JSON.stringify(call_data_json)));
              window.location.href = url;
            }
          }
          else{
            const ul_errors = document.getElementById('error-agregar-contacto');
            ul_errors.innerHTML = '';
            errors = respuesta['errors'];
            for( let key in errors){
              let li_error = document.createElement('li');
              li_error.innerHTML = `${key} - ${errors[key]}`;
              console.log(li_error);
              ul_errors.appendChild(li_error);
            }
          }
				}
        else{
          toastr.error('Error al crear el contacto, por favor contacte con su administrador');
        }
			});
      // $("#modal-agregar-contacto").modal('hide');
    });

  });

</script>
{% endblock %}