custom_client/urls.py
from rest_framework import routers
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from .views import programacion as programacion_views
from .views import conmutadores
from .views import reportes as reportes_views

urlpatterns = [

    # ========================== PROGRAMACIONES ===============================
    path(
        'shaio/programacion/list/',
        programacion_views.ProgramacionListView.as_view(),
        name='tc-shaio-programacion-list'
    ),
    path(
        'shaio/programacion/add/',
        programacion_views.ProgramacionAddView.as_view(),
        name='tc-shaio-programacion-add'
    ),
    path('shaio/programacion/<int:pk>/update/',
        programacion_views.ProgramacionUpdateView.as_view(),
        name='tc-shaio-programacion-update'
    ),
    path('shaio/programacion/<int:pk>/gestionar/',
        programacion_views.ProgramacionGestionarView.as_view(),
        name='tc-shaio-programacion-gestionar'
    ),
    path(
        'shaio/programacion/export/',
        programacion_views.ProgramacionListExportView.as_view(),
        name='tc-shaio-programacion-export'
    ),
    path(
        'campanas/programacion/manual/',
        programacion_views.CampanasProgramacionManual.as_view(),
        name='tc-campanas-programacion-manual'
    ),

    # ============================= REPORTES ==================================
    path(
        'sanautos/soat/reportes/',
        reportes_views.DashboardSoatView.as_view(),
        name='tc-sanautos-soat'
    ),
    # ============================ Conmutador ================================
    path(
        'conmutador/identificar_directorio/', 
        conmutadores.IdentificarDirecctorioLlamadaView.as_view(),
        name="tc_identificar_directorio"
    ),
    path(
        'conmutador/gestionar/',
        conmutadores.ConmutadorGestionView.as_view(),
        name="tc_conmutador_gestionar"
    ),
    path(
        'conmutador/cargar_gestion/',
        conmutadores.CargarGestionConmutadorView.as_view(),
        name="tc_cargar_gestion_conmutador"
    ),
    path(
        'conmutador/consultar_telefono/',
        conmutadores.ConsularTelefonoView.as_view(),
        name="tc_consultar_telefono_directorio"
    ),
    path(
        'conmutador/crear_directorio/',
        conmutadores.CrearDirectorioView.as_view(),
        name="tc_crear_directorio"
    ),
    path(
        'conmutador/obtener_telefonos_directorio/',
        conmutadores.ObtenerTelefonosDirectorio.as_view(),
        name="tc_obtener_telefonos_directorio"
    ),
    path(
        'conmutador/guardar_gestion/',
        conmutadores.GuardarGestionView.as_view(),
        name="tc_guardar_gestion_conmutador"
    ),
    path(
        'conmutador/consultar_directorio/',
        conmutadores.ConsultarDirectorioView.as_view(),
        name='tc_directorio_ver'
    ),
    path(
        'conmutador/modificar_directorio/',
        conmutadores.ModificarDirectorioView.as_view(),
        name='tc_modificar_directorio'
    ),
    path(
        'conmutador/eliminar_telefono/',
        conmutadores.EliminarTelefonoDirectorioView.as_view(),
        name='tc_eliminar_telefono_directorio'
    ),
    path(
        'conmutador/listar_gestiones/',
        conmutadores.GestionesConmutadorListView.as_view(),
        name='tc_gestiones_conmutador_list'
    ),
    path(
        'conmutador/listar_directorios/',
        conmutadores.DirectorioListView.as_view(),
        name='tc_directorios_list'
    )
]

custom_client/models/conmutadores.py
""" Modelo para el formulario de la campaña de conmutador. """

# Django
from django.db import models

# Omnileads
from ominicontacto_app.models import User, Campana
from reportes_app.models import LlamadaLog

# TrueContact
from truecontact.contactos.models import MEDIO_GESTION, TipoGestion, ESTADO_GESTION

# Utilidades
import ast


class BaseModel(models.Model):
    """ Modelo base.
    
    BaseModel actúa como una clase base abstracta de la que heredarán todos los demás modelos del proyecto. 
    Esta clase proporciona a cada tabla los siguientes atributos:

         + created (DateTime): Almacena la fecha y hora en que se creó el objeto.
         + modified (DateTime): Almacena la última fecha y hora en que se modificó el objeto.
    """

    created = models.DateTimeField(
        'create at',
        auto_now_add=True,
        help_text='Fecha y hora en la cual el objeto fue creado.'
    )

    modified = models.DateTimeField(
        'modified at',
        auto_now=True,
        help_text='Fecha y hora de la última modificación del objeto.'
    )

    class Meta:
        """ Opciones Meta. """
        abstract = True

        get_latest_by = 'created'
        ordering = ['-created', '-modified']

class Directorio(BaseModel):
    """ Modelo para el directorio de las diferentes áreas. """
    nombre = models.CharField(max_length=128)
    is_active = models.BooleanField('Directorio activo', default=True, blank=True, null=True)

    def __str__(self):
        """ Retorna el nombre del directorio """
        return self.nombre

    def obtener_telefonos(self):
        lista_telefonos = []

        for dato_contacto in DatosDirectorio.objects.filter(
            directorio=self).exclude(is_active=False):

            lista_telefonos.append(
                {
                    'id': dato_contacto.pk,
                    'label': dato_contacto.label,
                    'telefono': dato_contacto.numero,
                    'telefono_mask': 'x'*6 + dato_contacto.numero[-4:]
                }
            )

        return lista_telefonos

    def obtener_gestiones_pendientes(self):
        directorio_gestiones = Conmutador.objects.filter(directorio=self.pk).exclude(estado='finalizado')
        return directorio_gestiones

OPTION_DATO_DIRECTORIO = [
    ('casa', 'Casa'),
    ('oficina', 'Oficina'),
    ('extension', 'Extensión'),
    ('otro', 'Otro'),
]

class DatosDirectorio(BaseModel):
    """ Datos del directorio """
    directorio = models.ForeignKey(Directorio, on_delete=models.PROTECT)
    label = models.CharField(max_length=32, choices=OPTION_DATO_DIRECTORIO, default='otro')
    numero = models.CharField(max_length=20)
    is_active = models.BooleanField('Dato activo',default=True)

    def __str__(self):
        """ Retorna el id del dato y el nombre del directorio al que pertenece. """   
        return "Dato {} del directorio {}".format(self.id, self.directorio.nombre)

RESULTADO_CONMUTADOR = [
    ('efectiva', 'Llamada efectiva'),
    ('mensaje', 'Mensaje a tercero'),
    ('transferencia', 'Llamada transferida'),
    ('radio', 'Mensaje por radio'),
]

class Conmutador(BaseModel):
    nombre = models.CharField('Quién llama', max_length=255, blank=True, null=True)
    directorio = models.ForeignKey(Directorio, on_delete=models.PROTECT, related_name="directorio_origen")
    directorio_destino = models.ForeignKey(Directorio, on_delete=models.PROTECT, related_name="directorio_destino", blank=True, null=True)
    telefono = models.ForeignKey(DatosDirectorio, on_delete=models.PROTECT, blank=True, null=True)
    resultado = models.CharField(max_length=32, choices=RESULTADO_CONMUTADOR, blank=True, null=True)
    observaciones = models.TextField(blank=True, null=True)
    estado = models.CharField('Estado de la gestión', max_length=16, choices=ESTADO_GESTION, default="pendiente")
    tipo = models.ForeignKey(TipoGestion, on_delete=models.PROTECT,  blank=True, null=True)
    medio = models.CharField(max_length=64, choices=MEDIO_GESTION, default='otro')
    creado_por = models.ForeignKey(User, models.DO_NOTHING, blank=True, null=True, related_name="conmutador_creado_por")
    metadata = models.TextField(default='no_data')

    def __str__(self):
        """ Retorna el id del conmutador. """
        return str(self.id)
    
    def get_url_grabacion(self):
        INCLUDED_EVENTS = ['COMPLETEAGENT', 'COMPLETEOUTNUM', 'BT-COMPLETE',
                           'COMPLETE-BT', 'CT-COMPLETE', 'COMPLETE-CT', 'CAMPT-COMPLETE',
                           'COMPLETE-CAMPT', 'BTOUT-COMPLETE', 'COMPLETE-BTOUT', 'CTOUT-COMPLETE',
                           'COMPLETE-CTOUT']

        call_data = ast.literal_eval(self.metadata)
        grabaciones = LlamadaLog.objects.filter(archivo_grabacion__isnull=False,
                                  duracion_llamada__gt=0,
                                  event__in=INCLUDED_EVENTS)

        grabaciones = grabaciones.exclude(
            archivo_grabacion='-1').exclude(event='ENTERQUEUE-TRANSFER')


        if (call_data['medio'] == 'telefonia'):

            if (grabaciones.filter(callid=call_data['call_id']).exists()):
                grabacion = grabaciones.filter(callid=call_data['call_id'])[0]
                return grabacion.url_archivo_grabacion

            else:
                return ''
        else:
            return ''

    def obtener_campana(self):
        call_data = ast.literal_eval(self.metadata)
        if 'id_campana' in call_data:
            campana_pk = call_data['id_campana']
            nombre = Campana.objects.get(pk=campana_pk).nombre
        else:
            nombre = ""
        return str(nombre)
    
    def get_call_id(self):
        call_data = ast.literal_eval(self.metadata)
        if 'call_id' in call_data:
            call_id = call_data['call_id']
        else:
            call_id = ''
        return str(call_id)

custom_client/forms/conmutador_form.py
""" Formulario para la campaña de conmutador. """

# Django
from django import forms

# Modelo de conmutador
from truecontact.custom_client.models import Conmutador

class ConmutadorForm(forms.ModelForm):
    class Meta:
        model = Conmutador
        fields = ['tipo', 'medio', 'nombre', 'directorio_destino', 'telefono', 'resultado', 'observaciones']

custom_client/templates/conmutador/gestiones_conmutador_list.html
{% extends 'truecontact/base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% load template_extrafunc %}
{% block page_css_level %}
{% endblock %}

{% block content %}
<div class="widget-content-area custom-card p-0">

  <div class="row layout-spacing">
      <div class="col-lg-12">

          <div class="statbox widget box box-shadow">
              <div class="content-header pl-3 pr-3">

                  <div class="row mt-2">
                    <div class="col-sm-12">
                      <h2 class="text-muted">Gestiones realizadas</h2>
                      <div class="crumbs">
                        <ul id="breadcrumbs" class="breadcrumb">
                          <li><a href="javascript: void(0);"><i class="flaticon-home-fill"></i></a></li>
                          <li><a href="javascript: void(0);">Gestiones</a></li>
                          <!-- <li class="active"><a href="#">Products</a></li> -->
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                      <div class="col-xl-12 col-md-12 col-12">

                        <form class="" action="" method="get">
                          Filtro por fechas
                          <div class="row">
                            <div class="col-sm-6">
                               <div class="input-group col-sm-8">
                                  <div class="input-group-prepend">
                                    <span class="input-group-text">
                                      <i class="far fa-calendar-alt"> DESDE</i>
                                    </span>
                                  </div>
                                  <input type="date" class="form-control float-right" id="f_inicial" name="f_inicial" value="{{f_inicial}}" placeholder="dia/mes/año " >
                                </div>
                              <div class="input-group col-sm-8">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">
                                    <i class="far fa-calendar-alt"> HASTA</i>
                                  </span>
                                </div>
                                <input type="date" class="form-control float-right" id="f_final" name ="f_final" value="{{f_final}}" placeholder="dia/mes/año" >
                              </div>
                            </div>
                            <div class="col-sm-6">
                              <div class="input-group input-group-sm">
                                <input type="text" name="buscar" class="form-control" value="{{ buscar }}" placeholder="agente, documento, nombres, telefono">
                                <span class="input-group-append">
                                  <button type="submit" class="btn btn-info btn-flat">Buscar</button>
                                  {% if buscar %}
                                  <a href="{% url 'tc_gestiones_conmutador_list' %}" class="btn btn-warning float-right">
                                        Borrar
                                  </a>
                                  {% endif %}
                                </span>
                              </div>
                            </div>
                          </div>
                          <br>
                          <button type="submit" class="btn btn-info">Filtrar</button>
                          {% if f_final %}
                          <a href="{% url 'tc_gestiones_conmutador_list' %}" class="btn btn-default">
                                Borrar Filtro Fecha
                          </a>
                          {% endif %}
                          <a href="{% url 'tc-csv-gestiones' %}?buscar={{buscar}}{{filtro}}" class="btn btn-success float-right">
                            Descargar informe CSV
                          </a>

                        </form>

                      </div>


                  </div>
              </div>

              <div class="widget-content widget-content-area">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped table-checkable table-highlight-head mb-4">
                        <thead>
                            <tr>
                                <th class="">ID</th>
                                <th class="">Nombre</th>
                                <th class="">Directorio</th>
                                <th class="">Resultado</th>
                                <th class="">Fecha</th>
                                <th class="text-center">Accion</th>
                            </tr>
                        </thead>
                        <tbody>
                          {% for gestion in gestiones %}
                            <tr>
                              <td>{{ gestion.pk}}    </td>
                              <td>{{ gestion.nombre }}</td>
                              <td>{{ gestion.directorio.nombre }}</td>
                              <td>{{ gestion.get_resultado_display }}</td>
                              <td>{{ gestion.created|date:"d-m, Y, h:i A"}}</td>
                              <td class="d-flex justify-content-around">
                                {% if gestion.estado == 'pendiente' %}
                                  <span class="badge bg-warning">{{ gestion.get_estado_display }}</span>
                                {% elif gestion.estado == 'finalizado' %}
                                  <span class="badge bg-success">{{ gestion.get_estado_display }}</span>
                                {% else %}
                                  <span class="badge bg-danger">Error</span>
                                {% endif %}
                                <a id="ver_gestion_{{getion.pk}}" onclick="parent.verGestionConmutador('{{gestion.pk}}')" class="text-muted lead ml-1" data-id="{{ gestion.pk }}">
                                  <small>Ver</small>  <i class="fas fa-eye"></i>
                                </a>
                              </td>
                            </tr>
                          {% endfor %}

                        </tbody>
                    </table>
                </div>
              </div>
            </div>


          </div>

      </div>

      <div class="col-lg-12">
          <div class="statbox widget box box-shadow">
              <div class="widget-content widget-content-area text-right">
                <!-------     PAGINATOR DE LAS GESTIONES............  -->
                <div class="card-footer clearfix">
                  <span class="float-left">
                    Total Gestiones: {{ paginator.count }}
                  </span>
                  <br>
                  <span class="current">
                    Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if is_paginated %}
                  <div class="dataTables_paginate paging_simple_numbers">
                    <ul class="pagination pagination-style-2 pagination-rounded justify-content-center mb-5">
                      {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}{{filtro}}&buscar={{ buscar }}">«</a></li>
                      {% endif %}
                      {% for i in pages %}
                        {% if i == page_obj.number %}
                        <li><a class="active" href="#">{{ i }}</a></li>
                        {% else %}
                        <li><a href="?page={{ i }}{{filtro}}&buscar={{ buscar }}">{{ i }}</a></li>
                        {% endif %}
                      {% endfor %}
                      {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}{{filtro}}&buscar={{ buscar }}">»</a></li>
                      {% endif %}
                    </ul>
                    {% endif %}
                  </div>
                </div>           <!-------    end del PAGINATOR DE LAS GESTIONES............  -->


              </div>
          </div>
      </div>
  </div>
</div>

<script>
</script>
{% endblock %}